### PR TITLE
Run tests against Django 2.2

### PR DESCRIPTION
**Pull request by michael-k**

### CODE REVIEW

**Comment by michael-k** [comment]
I have no idea why the db tables do not exist :/

**Comment by jmsmkn** [comment]
Thanks! It seem like there is a problem with the sqlite3 version. On my machine this PR works fine, on travis it does not. So I set up circle CI, it also fails, but I can ssh into those build nodes. 

On my machine `import sqlite3; sqlite3.sqlite_version` is `3.22.0`. 

On circle CI its `3.16.2`. I added `deb http://ftp.debian.org/debian stretch-backports main` to `/etc/apt/sources.list` and upgraded sqlite3 with `sudo apt-get -t stretch-backports install sqlite3`. `sqlite3.sqlite_version` is now `3.26.0`. The django 2.2 test then pass, but it breaks the django 1.11 tests. I still need to debug this some more.

**Comment by jmsmkn** [comment]
I think that this has been solved upstream now, but will require some changes to the travis build. I will do this now.

**Comment by jmsmkn** [comment]
Thanks!

**Pull request merged**
